/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package widget;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author unknown
 */
public class WidgetGUI extends javax.swing.JFrame {

    /**
     * Creates new form WidgetGUI
     */
    int posX=0;
    int posY=0;
    public WidgetGUI() {
        setUndecorated(true);
        initComponents();
        this.setLocation(posX+415, posX+5);
        this.addMouseListener(new MouseAdapter()
        {
            public void mousePressed(MouseEvent e)
            {
                posX=e.getX();
                posY=e.getY();
            }
        });
        this.addMouseMotionListener(new MouseAdapter()
        {
            public void mouseDragged(MouseEvent evt)
            {			
		setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);			
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        exit_button = new javax.swing.JButton();
        facebook_button = new javax.swing.JLabel();
        TikTok_Button = new javax.swing.JLabel();
        twitter_Button = new javax.swing.JLabel();
        Linkedin_Button = new javax.swing.JLabel();
        instagram_Button = new javax.swing.JLabel();
        Youtube_Button1 = new javax.swing.JLabel();
        Bg_img = new javax.swing.JLabel();
        Facebook_desc = new javax.swing.JLabel();
        TikTok_desc = new javax.swing.JLabel();
        Twitter_desc = new javax.swing.JLabel();
        Linkedin_desc = new javax.swing.JLabel();
        Youtube_desc = new javax.swing.JLabel();
        Instagram_desc = new javax.swing.JLabel();
        Move_window = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 33, 61), 2, true));

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/icon-close.png"))); // NOI18N
        exit_button.setBorderPainted(false);
        exit_button.setContentAreaFilled(false);
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        facebook_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/facebook_img.png"))); // NOI18N
        facebook_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                facebook_buttonMouseReleased(evt);
            }
        });

        TikTok_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/tiktok-img.png"))); // NOI18N
        TikTok_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TikTok_ButtonMouseReleased(evt);
            }
        });

        twitter_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/twitter_img.png"))); // NOI18N
        twitter_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                twitter_ButtonMouseReleased(evt);
            }
        });

        Linkedin_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/linkedin_img.png"))); // NOI18N
        Linkedin_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Linkedin_ButtonMouseReleased(evt);
            }
        });

        instagram_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/instagram_img.png"))); // NOI18N
        instagram_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                instagram_ButtonMouseReleased(evt);
            }
        });

        Youtube_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/youtube_img.png"))); // NOI18N
        Youtube_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Youtube_Button1MouseReleased(evt);
            }
        });

        Bg_img.setBackground(new java.awt.Color(0, 0, 0));
        Bg_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bg_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widget/images/bg_img.jpg"))); // NOI18N
        Bg_img.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Bg_img.setPreferredSize(new java.awt.Dimension(700, 100));
        Bg_img.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Facebook_desc.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Facebook_desc.setText("Facebook");

        TikTok_desc.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TikTok_desc.setText("TikTok");

        Twitter_desc.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Twitter_desc.setText("Twitter");

        Linkedin_desc.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Linkedin_desc.setText("Linkedin");

        Youtube_desc.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Youtube_desc.setText("Youtube");

        Instagram_desc.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Instagram_desc.setText("instagram");

        Move_window.setFont(new java.awt.Font("Balthazar", 0, 18)); // NOI18N
        Move_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Move_window.setText("Move Window");
        Move_window.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 33, 61), 3));

        jLayeredPane1.setLayer(exit_button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(facebook_button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TikTok_Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(twitter_Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Linkedin_Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(instagram_Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Youtube_Button1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Bg_img, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Facebook_desc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TikTok_desc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Twitter_desc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Linkedin_desc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Youtube_desc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Instagram_desc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Move_window, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(Facebook_desc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(facebook_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(TikTok_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TikTok_desc)))
                        .addGap(9, 9, 9)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(twitter_Button)
                            .addComponent(Twitter_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Linkedin_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Youtube_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(Linkedin_desc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Youtube_desc)))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(instagram_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(Instagram_desc)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Move_window, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Bg_img, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(instagram_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Youtube_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Linkedin_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twitter_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TikTok_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(facebook_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Facebook_desc)
                            .addComponent(TikTok_desc)
                            .addComponent(Twitter_desc)
                            .addComponent(Linkedin_desc)
                            .addComponent(Youtube_desc)
                            .addComponent(Instagram_desc))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Move_window)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(Bg_img, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Youtube_Button1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Youtube_Button1MouseReleased
        try {
            Desktop.getDesktop().browse(URI.create("https://www.youtube.com"));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "something is Wrong :(");
        }
    }//GEN-LAST:event_Youtube_Button1MouseReleased

    private void instagram_ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagram_ButtonMouseReleased
        try {
            Desktop.getDesktop().browse(URI.create("https://www.instagram.com/"));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "something is Wrong :(");
        }
    }//GEN-LAST:event_instagram_ButtonMouseReleased

    private void Linkedin_ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Linkedin_ButtonMouseReleased
        try {
            Desktop.getDesktop().browse(URI.create("https://www.linkedin.com/"));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "something is Wrong :(");
        }
    }//GEN-LAST:event_Linkedin_ButtonMouseReleased

    private void twitter_ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitter_ButtonMouseReleased
        try {
            Desktop.getDesktop().browse(URI.create("https://twitter.com/"));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "something is Wrong :(");
        }
    }//GEN-LAST:event_twitter_ButtonMouseReleased

    private void TikTok_ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TikTok_ButtonMouseReleased
        try {
            Desktop.getDesktop().browse(URI.create("https://www.tiktok.com/"));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "something is Wrong :(");
        }
    }//GEN-LAST:event_TikTok_ButtonMouseReleased

    private void facebook_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebook_buttonMouseReleased
        try {
            Desktop.getDesktop().browse(URI.create("https://www.facebook.com/"));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something is Wrong :(");
        }
    }//GEN-LAST:event_facebook_buttonMouseReleased

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WidgetGUI().setVisible(true);
             
                }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg_img;
    private javax.swing.JLabel Facebook_desc;
    private javax.swing.JLabel Instagram_desc;
    private javax.swing.JLabel Linkedin_Button;
    private javax.swing.JLabel Linkedin_desc;
    private javax.swing.JLabel Move_window;
    private javax.swing.JLabel TikTok_Button;
    private javax.swing.JLabel TikTok_desc;
    private javax.swing.JLabel Twitter_desc;
    private javax.swing.JLabel Youtube_Button1;
    private javax.swing.JLabel Youtube_desc;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel facebook_button;
    private javax.swing.JLabel instagram_Button;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel twitter_Button;
    // End of variables declaration//GEN-END:variables
}


